In [ ]:
import os 
import math 
import re 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.experimental import enable_iterative_imputer
# for preprocessing and Feature engineering
from sklearn.impute import (
    SimpleImputer,
    KNNImputer
)
from sklearn.feature_selection import(
    SelectKBest,
    SelectPercentile,
    RFE,
    RFECV,
    VarianceThreshold
)

from sklearn.preprocessing import (
    OneHotEncoder,
    MinMaxScaler,
    StandardScaler,
    RobustScaler,
    Normalizer,
    PolynomialFeatures,
    OrdinalEncoder,
    LabelEncoder,
    KBinsDiscretizer,
    FunctionTransformer
)

# Model Selection and Evaluation

from sklearn.model_selection import (
    train_test_split,
    cross_val_predict,
    cross_val_score,
    GridSearchCV,
    RandomizedSearchCV,
    StratifiedKFold,
    KFold,
    cross_validate
)

from sklearn.metrics import (
    accuracy_score,
    precision_recall_curve,
    roc_auc_score,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
    root_mean_squared_error,
    confusion_matrix,
    r2_score,
    classification_report,
    f1_score,
    recall_score,
    explained_variance_score,
    precision_score
)

# For Regression
from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet,
    BayesianRidge,
    SGDRegressor,
    PassiveAggressiveRegressor
)

from sklearn.tree import (
    DecisionTreeRegressor,
)

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor,
    ExtraTreesRegressor,
    BaggingRegressor
)

from sklearn.svm import (
    SVR,
    LinearSVR

)

from sklearn.neighbors import (
    KNeighborsRegressor,
)

from sklearn.neural_network import (
    MLPRegressor,
    _multilayer_perceptron
)


# For Classification
from sklearn.linear_model import (
    LogisticRegression,
    RidgeClassifier,
    Perceptron,
    PassiveAggressiveClassifier,
    SGDClassifier
)

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier,
    BaggingClassifier
)

from sklearn.svm import (
    SVC,
    LinearSVC,
    NuSVC
)

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import (
    GaussianNB,
    MultinomialNB,
    BernoulliNB,
    CategoricalNB,
    ComplementNB
)

from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import (
    QuadraticDiscriminantAnalysis,
    LinearDiscriminantAnalysis
)
from sklearn.impute import IterativeImputer

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import scipy.stats as stats

from scipy.stats import(
anderson,
jarque_bera,
shapiro,
normaltest,
kstest
)
from statsmodels.stats.diagnostic import lilliefors

from scipy.stats import zscore

from sklearn.feature_extraction import FeatureHasher

from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.base import BaseEstimator, TransformerMixin

### Load dataset

In [11]:
path= os.path.join('..','data','raw','Used_Cars.csv')
df= pd.read_csv(path)

In [12]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [13]:
df.sample(5)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
2971,Ferrari,488 Spider Base,2019,"9,005 mi.",Gasoline,3.9L V8 32V GDI DOHC Twin Turbo,7-Speed Automatic with Auto-Shift,White,–,None reported,NaN,"$319,900"
48,Toyota,Avalon Touring,2016,"89,148 mi.",Gasoline,268.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,"$17,500"
2031,Mazda,CX-7 Sport,2009,"113,000 mi.",Gasoline,244.0HP 2.3L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Gray,Black,None reported,Yes,"$5,499"
3168,Volkswagen,e-Golf SE,2016,"41,615 mi.",NaN,115.0HP Electric Motor Electric Fuel System,1-Speed A/T,Blue,Gray,None reported,Yes,"$12,000"
1583,Chevrolet,Suburban 1500 LT,2008,"162,750 mi.",Gasoline,320.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,Transmission Overdrive Switch,White,Black,At least 1 accident or damage reported,Yes,"$7,200"

In [14]:
df.describe(include='all')

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
count,4009,4009,4009.000000,4009,3839,4009,4009,4009,4009,3896,3413,4009
unique,57,1898,NaN,2818,7,1146,62,319,156,2,1,1569
top,Ford,M3 Base,NaN,"110,000 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,A/T,Black,Black,None reported,Yes,"$15,000"
freq,386,30,NaN,16,3309,52,1037,905,2025,2910,3413,39
mean,NaN,NaN,2015.515590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,6.104816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 376.0 KB

In [16]:
df[df['brand']=='BMW']

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
7,BMW,740 iL,2001,"242,000 mi.",Gasoline,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Green,Green,None reported,Yes,"$7,300"
22,BMW,440 Gran Coupe 440i xDrive,2020,"25,990 mi.",Gasoline,3.0 Liter Turbo,Automatic,White,Beige,None reported,NaN,"$38,598"
28,BMW,650 Gran Coupe i xDrive,2015,"69,000 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Gray,Black,None reported,Yes,"$25,700"
32,BMW,i3 120Ah w/Range Extender,2020,"35,035 mi.",Hybrid,120 AH,Automatic,Black,Black,None reported,NaN,"$24,998"
36,BMW,340 i,2018,"44,261 mi.",Gasoline,3.0 Liter Turbo,Automatic,Gray,Black,None reported,NaN,"$33,598"
39,BMW,Z4 sDrive28i,2014,"70,000 mi.",Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,Beige,At least 1 accident or damage reported,Yes,"$20,000"
43,BMW,M850 i xDrive,2019,"9,949 mi.",Gasoline,4.4 Liter DOHC Twin Turbo,Automatic,Blue,Black,None reported,NaN,"$75,798"
65,BMW,X4 M40i,2023,"8,500 mi.",Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Beige,None reported,Yes,"$67,900"
66,BMW,M4 CS,2019,"19,069 mi.",Gasoline,3.0 Liter DOHC Turbo,Automatic,Alpine White,Anthracite,None reported,NaN,"$69,998"
72,BMW,M4 Base,2019,"57,800 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Red,None reported,Yes,"$55,999"
86,BMW,740 Li,2012,"85,252 mi.",Gasoline,326.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,Black,Black,None reported,Yes,"$18,500"
88,BMW,M6 Base,2016,"25,500 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,"$55,000"
95,BMW,435 Gran Coupe i,2016,"76,009 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Beige,None reported,Yes,"$24,950"
98,BMW,525 i,2005,"91,420 mi.",Gasoline,215.0HP 2.5L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,Black,Black,None reported,Yes,"$8,900"
103,BMW,i8 Base,2019,"41,500 mi.",Plug-In Hybrid,369.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,"$86,000"
106,BMW,540 i xDrive,2020,"27,158 mi.",Gasoline,2.0 Liter Turbo,Automatic,Imperial Blue Metallic,Canberra Beige/Black,None reported,NaN,"$39,998"
109,BMW,Z4 sDrive28i,2014,"36,812 mi.",Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,"$27,000"
112,BMW,750 750i xDrive,2021,"10,917 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,Black,Black,None reported,NaN,"$73,998"
132,BMW,650 Gran Coupe i xDrive,2015,"41,000 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,"$30,000"
136,BMW,X7 xDrive40i,2019,"35,248 mi.",Gasoline,3.0 Liter Twin Turbo,Automatic,Arctic Gray Metallic,Black,None reported,NaN,"$53,998"
145,BMW,M5 Base,2013,"86,000 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,White,None reported,Yes,"$32,000"
200,BMW,X5 3.0i,2004,"140,000 mi.",Gasoline,225.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Beige,None reported,Yes,"$6,730"
214,BMW,440 Gran Coupe i,2018,"39,300 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Beige,At least 1 accident or damage reported,Yes,"$31,750"
235,BMW,M6 Base,2016,"45,800 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Gold,Black,NaN,NaN,"$36,800"
237,BMW,X6 sDrive35i,2016,"70,582 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Black,White,At least 1 accident or damage reported,Yes,"$35,000"
291,BMW,M8 Competition,2020,"10,906 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,Donington Grey Metallic,Black,None reported,NaN,"$96,998"
293,BMW,i8 Base,2015,846 mi.,Plug-In Hybrid,357.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,A/T,White,White,None reported,Yes,"$86,999"
319,BMW,640 i,2016,"40,080 mi.",Gasoline,315.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Black,Black,None reported,Yes,"$28,499"
324,BMW,M4 Base,2016,"62,500 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,7-Speed A/T,Black,Orange,At least 1 accident or damage reported,Yes,"$40,500"
327,BMW,M550 i xDrive,2020,"40,000 mi.",Gasoline,523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,Black,None reported,Yes,"$53,000"
336,BMW,540 i xDrive,2020,"37,426 mi.",Gasoline,2.0 Liter Turbo,Automatic,White,Black,None reported,NaN,"$39,998"
342,BMW,X1 sDrive28i,2014,"50,100 mi.",Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Brown,Beige,None reported,Yes,"$10,795"
345,BMW,M4 Base,2015,"26,600 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,White,–,None reported,Yes,"$53,000"
349,BMW,X6 xDrive40i,2020,"45,076 mi.",Gasoline,3.0 Liter Turbo,Automatic,Blue,Black,None reported,NaN,"$57,998"
358,BMW,X1 xDrive28i,2020,"18,200 mi.",Gasoline,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,White,Beige,At least 1 accident or damage reported,Yes,"$29,500"
365,BMW,328 xi,2007,"83,000 mi.",Gasoline,230.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,Black,Brown,None reported,Yes,"$8,995"
368,BMW,M235 i,2014,"125,450 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Blue,Black,None reported,Yes,"$17,200"
372,BMW,X3 xDrive30i,2021,"2,492 mi.",Gasoline,2.0 Liter Turbo,Automatic,Phytonic Blue Metallic,Canberra Beige/Black,None reported,NaN,"$41,598"
377,BMW,M5 Base,2018,"20,500 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Black,None reported,Yes,"$67,000"
386,BMW,440 i xDrive,2018,"73,500 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,Black,Blue,None reported,Yes,"$32,000"
389,BMW,M6 Base,2014,"29,500 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Silver,Black,None reported,Yes,"$40,999"
393,BMW,Z4 3.0i Roadster,2006,"46,508 mi.",Gasoline,215.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Green,Beige,At least 1 accident or damage reported,Yes,"$11,500"
394,BMW,M6 Base,2015,"18,651 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Red,Black,None reported,Yes,"$59,549"
395,BMW,X3 M40i,2019,"36,438 mi.",Gasoline,3.0 Liter Turbo,Automatic,Alpine White,Oyster W/Contrast,None reported,NaN,"$39,998"
398,BMW,Z4 sDrive28i,2015,"57,550 mi.",Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Black,White,None reported,Yes,"$29,995"
403,BMW,X7 xDrive40i,2023,"2,437 mi.",Hybrid,375.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Black,None reported,Yes,"$78,350"
442,BMW,750 Li xDrive,2012,"103,000 mi.",Gasoline,407.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,None reported,Yes,"$16,000"
443,BMW,M3 CS,2024,456 mi.,Gasoline,543.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$128,995"
448,BMW,750 i xDrive,2019,"28,744 mi.",Gasoline,4.4 Liter DOHC Twin Turbo,Automatic,Black,Black,None reported,NaN,"$50,998"
449,BMW,M3 Base,2015,"65,800 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,White,Red,None reported,Yes,"$44,950"
463,BMW,X5 M Base,2023,"4,348 mi.",Gasoline,4.4L V8 32V GDI DOHC Twin Turbo,8-Speed Automatic,Alpine White,Black,None reported,NaN,"$105,900"
473,BMW,M760 i xDrive,2021,"11,078 mi.",Gasoline,"6.6L V-12 gasoline direct injection, DOHC, var...","Automatic, 8-Spd Sport w/Sport & Manual Modes",BLACK,WHITE,None reported,NaN,"$91,900"
485,BMW,M3 Base,2009,"112,000 mi.",Gasoline,420.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Black,At least 1 accident or damage reported,Yes,"$28,000"
490,BMW,X2 xDrive28i,2022,"33,000 mi.",Gasoline,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Orange,Black,None reported,Yes,"$29,999"
505,BMW,X7 xDrive40i,2023,"2,950 mi.",Hybrid,375.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Black,Brown,None reported,Yes,"$87,000"
508,BMW,X1 xDrive28i,2021,"25,918 mi.",Gasoline,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Black,None reported,Yes,"$32,000"
509,BMW,135 i,2008,"87,000 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,White,Beige,None reported,Yes,"$15,300"
513,BMW,Z4 2.5i Roadster,2005,"138,000 mi.",Gasoline,184.0HP 2.5L Straight 6 Cylinder Engine Gasoli...,5-Speed A/T,White,Beige,None reported,Yes,"$9,950"
521,BMW,550 Gran Turismo i,2013,"79,341 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Gold,Brown,None reported,Yes,"$16,800"
523,BMW,430 i xDrive,2021,"16,900 mi.",Gasoline,255.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,8-Speed A/T,Blue,White,None reported,Yes,"$43,000"
566,BMW,M2 Base,2023,"1,160 mi.",Gasoline,453.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Gray,Black,None reported,Yes,"$73,600"
575,BMW,330e iPerformance,2017,"41,550 mi.",Plug-In Hybrid,247.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,Transmission w/Dual Shift Mode,Silver,Black,None reported,Yes,"$20,995"
583,BMW,X5 PHEV xDrive45e,2023,"5,338 mi.",Plug-In Hybrid,389.0HP 3.0L Straight 6 Cylinder Engine Plug-I...,8-Speed A/T,Blue,White,None reported,Yes,"$76,500"
585,BMW,X6 M Base,2018,"48,291 mi.",Gasoline,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,"$67,250"
601,BMW,M4 Base,2020,"22,655 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,7-Speed A/T,Silver,Black,None reported,Yes,"$63,999"
604,BMW,X6 M Base,2018,"48,000 mi.",Gasoline,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Blue,Black,None reported,Yes,"$54,000"
615,BMW,430 430i,2022,"7,758 mi.",Gasoline,2.0 Liter Turbo,Automatic,Black,Black,None reported,NaN,"$47,998"
628,BMW,ALPINA B7 ALPINA B7 xDrive,2020,"33,749 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,Blue,Red,None reported,NaN,"$85,998"
629,BMW,M4 Competition xDrive,2023,"1,120 mi.",Gasoline,503.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Gray,White,None reported,Yes,"$92,900"
633,BMW,X6 M Base,2022,"10,376 mi.",Gasoline,4.4L V8 32V GDI DOHC Twin Turbo,8-Speed Automatic,Ametrin Metallic,Black,None reported,NaN,"$98,900"
646,BMW,ALPINA B7 ALPINA B7 xDrive,2020,"65,852 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,Black,Mocha,None reported,NaN,"$68,998"
649,BMW,i8 Base,2019,"18,421 mi.",Plug-In Hybrid,369.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,6-Speed A/T,Black,Black,NaN,NaN,"$85,000"
667,BMW,M760 i xDrive,2019,"14,806 mi.",Gasoline,601.0HP 6.6L 12 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,At least 1 accident or damage reported,Yes,"$81,330"
680,BMW,X6 M Base,2023,"7,000 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Gray,None reported,Yes,"$144,900"
688,BMW,M240 i,2019,"19,300 mi.",Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Red,None reported,Yes,"$36,000"
702,BMW,330e iPerformance,2017,"52,500 mi.",Plug-In Hybrid,247.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,Transmission w/Dual Shift Mode,Blue,Black,At least 1 accident or damage reported,Yes,"$24,950"
707,BMW,X7 xDrive40i,2022,"38,671 mi.",Hybrid,3.0 Liter Turbo,Automatic,Gray,Blk,None reported,NaN,"$66,998"
714,BMW,328 i xDrive,2013,"96,000 mi.",Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,At least 1 accident or damage reported,Yes,"$13,500"
715,BMW,135 i,2009,"72,900 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,Gray,Gray,None reported,Yes,"$15,500"
716,BMW,X7 M50i,2021,"7,121 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,Gray,Black,None reported,NaN,"$94,998"
720,BMW,X7 xDrive40i,2021,"30,309 mi.",Hybrid,3.0 Liter Turbo,Automatic,Blue,Tan,None reported,NaN,"$63,598"
722,BMW,740 i,2016,"73,000 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$23,999"
726,BMW,X7 ALPINA XB7,2022,"4,514 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,Gray,Black,None reported,NaN,"$132,998"
730,BMW,M6 Base,2015,"37,000 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Silver,Silver,None reported,Yes,"$45,950"
733,BMW,X6 M Base,2021,"11,102 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,"$101,000"
735,BMW,X7 xDrive50i,2019,"31,157 mi.",Gasoline,4.4 Liter GDI DOHC Twin Turbo,Automatic,Black,Blk,None reported,NaN,"$65,998"
737,BMW,435 i,2014,"80,211 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,Gray,Red,At least 1 accident or damage reported,Yes,"$17,995"
740,BMW,740 i,2018,"40,989 mi.",Gasoline,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Black,Gold,None reported,Yes,"$35,000"
744,BMW,M3 Base,2011,"105,000 mi.",Gasoline,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,6-Speed M/T,Silver,Black,At least 1 accident or damage reported,Yes,"$21,900"
747,BMW,M3 Base,2011,"72,277 mi.",Gasoline,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Red,None reported,Yes,"$34,950"
751,BMW,M4 Base,2018,"19,600 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,7-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$62,000"
758,BMW,M6 Base,2014,"65,550 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,"$39,985"
763,BMW,M4 Base,2023,"15,000 mi.",Gasoline,"3L I-6 gasoline direct injection, DOHC, Double...","Automatic, 8-Spd M STEPTRONIC w/Drivelogic, Sp...",BLUE,ORANGE,None reported,NaN,"$81,000"
780,BMW,M440 i,2021,"13,700 mi.",Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Black,Beige,NaN,NaN,"$60,000"
789,BMW,X6 xDrive50i,2017,"78,500 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Red,Brown,At least 1 accident or damage reported,Yes,"$42,000"
805,BMW,M3 Base,2011,"114,890 mi.",Gasoline,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,"$20,990"
813,BMW,X5 xDrive40i,2019,"50,000 mi.",Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Blue,Gold,None reported,Yes,"$43,000"
823,BMW,M4 Base,2018,"19,300 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,White,Silver,None reported,Yes,"$64,000"
847,BMW,M440 i xDrive,2021,"24,300 mi.",Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Gray,Beige,None reported,Yes,"$49,999"
867,BMW,X5 eDrive xDrive40e,2018,"45,090 mi.",Plug-In Hybrid,313.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,8-Speed A/T,Gray,Black,At least 1 accident or damage reported,Yes,"$30,750"
873,BMW,M4 Base,2020,"29,140 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,M/T,Orange,Orange,None reported,Yes,"$71,995"
874,BMW,M340 i xDrive,2022,"9,000 mi.",Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,White,Red,None reported,Yes,"$56,900"
877,BMW,ALPINA B7 Base,2013,"36,750 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,"$35,999"
881,BMW,X5 M Base,2022,"8,307 mi.",Gasoline,4.4L V8 32V GDI DOHC Twin Turbo,8-Speed Automatic,Blue Metallic,Sakhir Orange,None reported,NaN,"$98,900"
882,BMW,M3 Base,2023,"4,106 mi.",Gasoline,3.0L I6 24V GDI DOHC Twin Turbo,6-Speed Manual,Isle of Man Green Metallic,Kyalami Orange,None reported,Yes,"$84,645"
883,BMW,M3 Base,1999,"184,700 mi.",Gasoline,240.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,5-Speed M/T,Blue,Gray,None reported,Yes,"$36,950"
900,BMW,M5 Base,2018,"47,700 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Red,White,At least 1 accident or damage reported,Yes,"$54,999"
922,BMW,435 i,2014,"53,600 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes,"$25,980"
934,BMW,M5 Base,2018,"31,090 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Green,Black,At least 1 accident or damage reported,Yes,"$68,000"
940,BMW,M6 Gran Coupe Base,2019,"20,500 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,Black,None reported,Yes,"$67,900"
942,BMW,650 i,2009,"35,000 mi.",Gasoline,360.0HP 4.8L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Black,None reported,Yes,"$18,500"
954,BMW,650 i,2012,"39,960 mi.",Gasoline,400.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,6-Speed M/T,White,Brown,None reported,Yes,"$38,995"
966,BMW,650 i,2014,"40,000 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,"$34,000"
972,BMW,X7 xDrive40i,2020,"45,241 mi.",Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,Blue,Brown,None reported,Yes,"$54,500"
986,BMW,M5 Base,2013,"61,145 mi.",Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Beige,At least 1 accident or damage reported,Yes,"$37,500"
991,BMW,540 i xDrive,2019,"36,000 mi.",Gasoline,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Gray,Black,At least 1 accident or damage reported,Yes,"$41,995"
992,BMW,X6 xDrive35i,2009,"92,008 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,White,Black,None reported,Yes,"$12,500"
1003,BMW,M4 Base,2018,"7,200 mi.",Gasoline,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,7-Speed A/T,Black,Black,None reported,Yes,"$64,000"
1006,BMW,M8 Base,2020,"25,520 mi.",Gasoline,4.4L V8 32V GDI DOHC Twin Turbo,8-Speed Automatic,Brands Hatch Gray Metallic,Black,None reported,NaN,"$84,900"
1032,BMW,750 i xDrive,2019,"41,906 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Blue,White,At least 1 accident or damage reported,Yes,"$45,999"
1057,BMW,X6 xDrive40i,2022,"13,000 mi.",Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Orange,None reported,Yes,"$69,000"
1095,BMW,750 i xDrive,2019,"33,499 mi.",Gasoline,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,At least 1 accident or damage reported,Yes,"$44,495"
1098,BMW,i3 Base w/Range Extender,2014,"29,553 mi.",NaN,170.0HP 0.65L Electric Motor Electric Fuel System,1-Speed A/T,Black,Gray,None reported,Yes,"$12,800"
1128,BMW,335 i,2010,"91,545 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed A/T,Black,Black,None reported,Yes,"$13,000"
1135,BMW,435 Gran Coupe i,2015,"60,100 mi.",Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Blue,Beige,None reported,Yes,"$24,995"
1147,BMW,M5 Base,2023,816 mi.,Gasoline,4.4L V8 32V GDI DOHC Twin Turbo,8-Speed Automatic,Alpine White,Black,None reported,NaN,"$109,900"
1151,BMW,M8 Competition,2022,"5,018 mi.",Gasoline,4.4 Liter Twin Turbo,Automatic,–,Sakhir Orange/Black,None reported,NaN,"$114,998"
1158,BMW,M5 Competition,2020,"35,400 mi.",Gasoline,617.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Orange,Black,None reported,Yes,"$71,950"
1163,BMW,M760 M760i xDrive,2020,"23,430 mi.",Gasoline,6.6 Liter Twin Turbo,Automatic,White,Black,None reported,NaN,"$80,998"
1170,BMW,X1 sDrive28i,2022,"43,000 mi.",Gasoline,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,8-Speed A/T,Gray,Black,None reported,Yes,"$35,750"
1190,BMW,M5 Base,2018,"41,000 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,White,None reported,Yes,"$60,200"
1198,BMW,528 i xDrive,2016,"134,000 mi.",Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Brown,Brown,At least 1 accident or damage reported,Yes,"$13,500"
1201,BMW,X6 M Base,2021,"18,000 mi.",Gasoline,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,None reported,Yes,"$94,000"

In [17]:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_colwidth', None)
#pd.set_option('display.max_columns', None)
df[df['brand'] == 'BMW'][['brand', 'engine', 'price', 'accident']]

,brand,engine,price,accident
7,BMW,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$7,300",None reported
22,BMW,3.0 Liter Turbo,"$38,598",None reported
28,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$25,700",None reported
32,BMW,120 AH,"$24,998",None reported
36,BMW,3.0 Liter Turbo,"$33,598",None reported
39,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$20,000",At least 1 accident or damage reported
43,BMW,4.4 Liter DOHC Twin Turbo,"$75,798",None reported
65,BMW,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$67,900",None reported
66,BMW,3.0 Liter DOHC Turbo,"$69,998",None reported
72,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$55,999",None reported
86,BMW,326.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$18,500",None reported
88,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$55,000",None reported
95,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$24,950",None reported
98,BMW,215.0HP 2.5L Straight 6 Cylinder Engine Gasoli...,"$8,900",None reported
103,BMW,369.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,"$86,000",None reported
106,BMW,2.0 Liter Turbo,"$39,998",None reported
109,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$27,000",None reported
112,BMW,4.4 Liter Twin Turbo,"$73,998",None reported
132,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$30,000",None reported
136,BMW,3.0 Liter Twin Turbo,"$53,998",None reported
145,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$32,000",None reported
200,BMW,225.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$6,730",None reported
214,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$31,750",At least 1 accident or damage reported
235,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$36,800",NaN
237,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$35,000",At least 1 accident or damage reported
291,BMW,4.4 Liter Twin Turbo,"$96,998",None reported
293,BMW,357.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,"$86,999",None reported
319,BMW,315.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$28,499",None reported
324,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$40,500",At least 1 accident or damage reported
327,BMW,523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$53,000",None reported
336,BMW,2.0 Liter Turbo,"$39,998",None reported
342,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$10,795",None reported
345,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$53,000",None reported
349,BMW,3.0 Liter Turbo,"$57,998",None reported
358,BMW,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$29,500",At least 1 accident or damage reported
365,BMW,230.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$8,995",None reported
368,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$17,200",None reported
372,BMW,2.0 Liter Turbo,"$41,598",None reported
377,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$67,000",None reported
386,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$32,000",None reported
389,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$40,999",None reported
393,BMW,215.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$11,500",At least 1 accident or damage reported
394,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$59,549",None reported
395,BMW,3.0 Liter Turbo,"$39,998",None reported
398,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$29,995",None reported
403,BMW,375.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$78,350",None reported
442,BMW,407.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$16,000",None reported
443,BMW,543.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$128,995",None reported
448,BMW,4.4 Liter DOHC Twin Turbo,"$50,998",None reported
449,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$44,950",None reported
463,BMW,4.4L V8 32V GDI DOHC Twin Turbo,"$105,900",None reported
473,BMW,"6.6L V-12 gasoline direct injection, DOHC, var...","$91,900",None reported
485,BMW,420.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$28,000",At least 1 accident or damage reported
490,BMW,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$29,999",None reported
505,BMW,375.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$87,000",None reported
508,BMW,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$32,000",None reported
509,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$15,300",None reported
513,BMW,184.0HP 2.5L Straight 6 Cylinder Engine Gasoli...,"$9,950",None reported
521,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$16,800",None reported
523,BMW,255.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$43,000",None reported
566,BMW,453.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$73,600",None reported
575,BMW,247.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$20,995",None reported
583,BMW,389.0HP 3.0L Straight 6 Cylinder Engine Plug-I...,"$76,500",None reported
585,BMW,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$67,250",None reported
601,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$63,999",None reported
604,BMW,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$54,000",None reported
615,BMW,2.0 Liter Turbo,"$47,998",None reported
628,BMW,4.4 Liter Twin Turbo,"$85,998",None reported
629,BMW,503.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$92,900",None reported
633,BMW,4.4L V8 32V GDI DOHC Twin Turbo,"$98,900",None reported
646,BMW,4.4 Liter Twin Turbo,"$68,998",None reported
649,BMW,369.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,"$85,000",NaN
667,BMW,601.0HP 6.6L 12 Cylinder Engine Gasoline Fuel,"$81,330",At least 1 accident or damage reported
680,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$144,900",None reported
688,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$36,000",None reported
702,BMW,247.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$24,950",At least 1 accident or damage reported
707,BMW,3.0 Liter Turbo,"$66,998",None reported
714,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$13,500",At least 1 accident or damage reported
715,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$15,500",None reported
716,BMW,4.4 Liter Twin Turbo,"$94,998",None reported
720,BMW,3.0 Liter Turbo,"$63,598",None reported
722,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$23,999",None reported
726,BMW,4.4 Liter Twin Turbo,"$132,998",None reported
730,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$45,950",None reported
733,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$101,000",None reported
735,BMW,4.4 Liter GDI DOHC Twin Turbo,"$65,998",None reported
737,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$17,995",At least 1 accident or damage reported
740,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$35,000",None reported
744,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$21,900",At least 1 accident or damage reported
747,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$34,950",None reported
751,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$62,000",At least 1 accident or damage reported
758,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$39,985",None reported
763,BMW,"3L I-6 gasoline direct injection, DOHC, Double...","$81,000",None reported
780,BMW,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$60,000",NaN
789,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$42,000",At least 1 accident or damage reported
805,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$20,990",None reported
813,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$43,000",None reported
823,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$64,000",None reported
847,BMW,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$49,999",None reported
867,BMW,313.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$30,750",At least 1 accident or damage reported
873,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$71,995",None reported
874,BMW,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$56,900",None reported
877,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$35,999",None reported
881,BMW,4.4L V8 32V GDI DOHC Twin Turbo,"$98,900",None reported
882,BMW,3.0L I6 24V GDI DOHC Twin Turbo,"$84,645",None reported
883,BMW,240.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$36,950",None reported
900,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$54,999",At least 1 accident or damage reported
922,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$25,980",None reported
934,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$68,000",At least 1 accident or damage reported
940,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$67,900",None reported
942,BMW,360.0HP 4.8L 8 Cylinder Engine Gasoline Fuel,"$18,500",None reported
954,BMW,400.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$38,995",None reported
966,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$34,000",None reported
972,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$54,500",None reported
986,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$37,500",At least 1 accident or damage reported
991,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$41,995",At least 1 accident or damage reported
992,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$12,500",None reported
1003,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$64,000",None reported
1006,BMW,4.4L V8 32V GDI DOHC Twin Turbo,"$84,900",None reported
1032,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$45,999",At least 1 accident or damage reported
1057,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$69,000",None reported
1095,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$44,495",At least 1 accident or damage reported
1098,BMW,170.0HP 0.65L Electric Motor Electric Fuel System,"$12,800",None reported
1128,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$13,000",None reported
1135,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$24,995",None reported
1147,BMW,4.4L V8 32V GDI DOHC Twin Turbo,"$109,900",None reported
1151,BMW,4.4 Liter Twin Turbo,"$114,998",None reported
1158,BMW,617.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$71,950",None reported
1163,BMW,6.6 Liter Twin Turbo,"$80,998",None reported
1170,BMW,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$35,750",None reported
1190,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$60,200",None reported
1198,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$13,500",At least 1 accident or damage reported
1201,BMW,600.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$94,000",None reported
1205,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$16,000",None reported
1213,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$40,000",None reported
1218,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$26,500",At least 1 accident or damage reported
1229,BMW,365.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$52,000",None reported
1238,BMW,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$29,000",At least 1 accident or damage reported
1249,BMW,405.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$55,000",None reported
1251,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$27,500",None reported
1273,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$64,995",None reported
1292,BMW,170.0HP 2.5L Straight 6 Cylinder Engine Gasoli...,"$2,500",None reported
1304,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$60,995",None reported
1314,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$46,999",At least 1 accident or damage reported
1321,BMW,555.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$17,000",At least 1 accident or damage reported
1323,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$40,000",None reported
1324,BMW,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$49,999",At least 1 accident or damage reported
1328,BMW,190.0HP 2.8L Straight 6 Cylinder Engine Gasoli...,"$15,900",At least 1 accident or damage reported
1333,BMW,375.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$85,495",None reported
1342,BMW,Intercooled Turbo Premium Unleaded I-4 2.0 L/122,"$31,698",None reported
1386,BMW,523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$66,000",NaN
1394,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$71,400",None reported
1399,BMW,405.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$70,000",None reported
1407,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$25,000",None reported
1408,BMW,288.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$47,000",None reported
1429,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$24,000",None reported
1442,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$28,000",None reported
1446,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$5,699",None reported
1461,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$18,500",None reported
1463,BMW,360.0HP 4.8L 8 Cylinder Engine Gasoline Fuel,"$8,000",None reported
1473,BMW,215.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$4,000",None reported
1495,BMW,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$46,000",None reported
1504,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$20,000",NaN
1507,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$11,000",None reported
1512,BMW,500.0HP 5.0L 10 Cylinder Engine Gasoline Fuel,"$19,500",None reported
1519,BMW,500.0HP 5.0L 10 Cylinder Engine Gasoline Fuel,"$21,000",None reported
1524,BMW,247.0HP 2.0L 4 Cylinder Engine Plug-In Electri...,"$24,995",None reported
1531,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$28,500",None reported
1553,BMW,255.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$37,000",None reported
1560,BMW,306.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$17,000",At least 1 accident or damage reported
1565,BMW,333.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$42,000",At least 1 accident or damage reported
1567,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$10,999",At least 1 accident or damage reported
1571,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$54,999",None reported
1572,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$85,000",None reported
1592,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$42,800",None reported
1600,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$9,999",None reported
1601,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$15,000",None reported
1603,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$12,999",None reported
1613,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$49,999",None reported
1630,BMW,260.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$8,500",None reported
1632,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$36,995",None reported
1646,BMW,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$26,999",None reported
1664,BMW,255.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$51,000",None reported
1682,BMW,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$48,600",At least 1 accident or damage reported
1691,BMW,543.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$145,000",None reported
1703,BMW,617.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$117,500",None reported
1711,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$19,500",At least 1 accident or damage reported
1715,BMW,320.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$29,000",None reported
1720,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$40,950",At least 1 accident or damage reported
1735,BMW,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$65,000",At least 1 accident or damage reported
1736,BMW,326.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$12,700",At least 1 accident or damage reported
1769,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$24,995",None reported
1783,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$41,250",None reported
1785,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$20,950",At least 1 accident or damage reported
1795,BMW,333.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$15,000",None reported
1797,BMW,315.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$22,500",At least 1 accident or damage reported
1807,BMW,382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$50,000",None reported
1822,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$27,899",None reported
1823,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$50,000",None reported
1826,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$27,499",None reported
1827,BMW,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$49,000",At least 1 accident or damage reported
1830,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$16,700",At least 1 accident or damage reported
1831,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$36,500",None reported
1839,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$12,975",None reported
1852,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$50,900",None reported
1853,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$23,000",At least 1 accident or damage reported
1859,BMW,503.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$84,995",None reported
1865,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$62,450",None reported
1872,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$19,996",At least 1 accident or damage reported
1923,BMW,333.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$25,000",None reported
1935,BMW,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$31,000",None reported
1944,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$55,000",None reported
1953,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$12,000",NaN
1962,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$29,999",None reported
1963,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$38,490",None reported
1980,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$20,999",At least 1 accident or damage reported
2002,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$32,000",None reported
2020,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$13,800",None reported
2022,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$32,999",None reported
2023,BMW,360.0HP 4.8L 8 Cylinder Engine Gasoline Fuel,"$7,300",At least 1 accident or damage reported
2059,BMW,315.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$26,000",At least 1 accident or damage reported
2080,BMW,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$24,000",At least 1 accident or damage reported
2085,BMW,503.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$95,580",None reported
2087,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$27,000",None reported
2130,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$15,000",None reported
2135,BMW,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,"$25,999",None reported
2150,BMW,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$26,999",At least 1 accident or damage reported
2154,BMW,425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$53,500",None reported
2156,BMW,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$19,950",None reported
2163,BMW,333.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$39,000",None reported
2199,BMW,2.0 Liter DOHC T/C,"$29,998",None reported
2208,BMW,315.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$22,500",None reported
2214,BMW,567.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$46,000",None reported
2225,BMW,503.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$89,995",None reported
2241,BMW,333.0HP 3.2L Straight 6 Cylinder Engine Gasoli...,"$21,000",None reported
2245,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$34,000",At least 1 accident or damage reported
2256,BMW,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$59,900",None reported
2258,BMW,326.0HP 5.4L 12 Cylinder Engine Gasoline Fuel,"$11,800",NaN
2264,BMW,540.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,"$29,000",At least 1 accident or damage reported
2275,BMW,357.0HP 1.5L 3 Cylinder Engine Plug-In Electri...,"$53,000",None reported
2284,BMW,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,"$18,300",None reported
2289,BMW,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,"$90,000",None reported
2300,BMW,4.4L V8 32V GDI DOHC Twin Turbo,"$86,900",None reported
2306,BMW,4.4 Liter Twin Turbo,"$99,998",None reported
2308,BMW,2.0 Liter Turbo,"$30,798",None reported

In [18]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [19]:
df.dtypes

brand             str
model             str
model_year      int64
milage            str
fuel_type         str
engine            str
transmission      str
ext_col           str
int_col           str
accident          str
clean_title       str
price             str
dtype: object

In [20]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

### Data Cleaning

In [21]:
df['milage']=(
    df['milage']
    .str.replace('mi.','')
    .str.replace(',','')
    .astype('float')
)

In [22]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [23]:
df['milage'].dtypes

dtype('float64')

In [24]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [25]:
df['price']=(
    df['price']
    .str.replace('$','')
    .str.replace(',','')
    .astype(float)
)

In [26]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0

In [27]:
df['Engine_Capacity']=(
    df['engine']
    .str.extract(r'(\d+\.\d+L|\d+L|\d+\.\d+\s+Liter|\d+\s+Liter)')
)

In [28]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Engine_Capacity
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,3.7L
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,3.8L
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,3.5 Liter
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0,3.5L
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,2.0L

In [29]:
df['Horse_Power']=(
    df['engine']
    .str.extract(r'(\d+\.\d+HP|\d+HP)')
)

In [30]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,3.7L,300.0HP
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,3.8L,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,3.5 Liter,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0,3.5L,354.0HP
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,2.0L,NaN

In [31]:
df['Engine_Capacity']=(
    df['Engine_Capacity']
    .str.replace('Liter','')
    .str.replace('L','')
    .astype(float)
)

In [32]:
df['Horse_Power']=(
    df['Horse_Power']
    .str.replace('HP','')
    .astype(float)
)

In [33]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,3.7,300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0,3.5,354.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,2.0,NaN

In [34]:
df['Accident_Occured']=(
    df['accident'].apply(lambda x:"NO" if x=="None reported" else "YES")
)

In [35]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Engine_Capacity,Horse_Power,Accident_Occured
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,3.7,300.0,YES
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,3.8,NaN,YES
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,3.5,NaN,NO
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,15500.0,3.5,354.0,NO
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,2.0,NaN,NO

In [36]:
df.drop('accident',axis=1,inplace=True)

In [37]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,clean_title,price,Engine_Capacity,Horse_Power,Accident_Occured
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,Yes,10300.0,3.7,300.0,YES
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,Yes,38005.0,3.8,NaN,YES
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,NaN,54598.0,3.5,NaN,NO
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,Yes,15500.0,3.5,354.0,NO
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,NaN,34999.0,2.0,NaN,NO

In [38]:
df.isna().sum()

brand                 0
model                 0
model_year            0
milage                0
fuel_type           170
engine                0
transmission          0
ext_col               0
int_col               0
clean_title         596
price                 0
Engine_Capacity     219
Horse_Power         808
Accident_Occured      0
dtype: int64

In [39]:
len(df.columns)

14

### Finding Missing Percentage

In [40]:
missing_info={}
for col in df.columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The columns with missing percentage is:\n")
for col, per in missing_info.items():
    print(f'{col}:{per}%')

 The columns with missing percentage is:

fuel_type:4.24%
clean_title:14.87%
Engine_Capacity:5.46%
Horse_Power:20.15%